### ISSUE TITLE
Problème avec l'affichage des images

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#14]
Présente dans mon profil mais pas dans les interfaces publiques ... 

Par ailleurs ca a déconné quand j'ai voulu mettre celle d'un projet ..

**Comment by GuillaumeAV** [comment]
Ca va mieux mais sur event, j'ai du raffraichir 2 fois pour que l'image s'affiche ..

**Comment by GuillaumeAV** [comment]
Par ailleurs, la je crée un projet et l'image de l'event est affichée par défaut ..

**Comment by SebLemoine** [comment]
Le problème est du au faut que tu créée une ressource vide mais avec une image

**Comment by GuillaumeAV** [comment]
Et il y a une solution ?
