### ISSUE TITLE
Pouvoir éditer les thesaurus type d'événements, type d'organisation, de projet, domaine d'activité

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#29]
On pourrait proposer : 

Soit d'éditer des thesaurus spécifiques, 
Soit charger des thesaurus disponibles sur le web via des uri ... Le plus intéressant naturellement ;-)

**Comment by SebLemoine** [comment]
spec de form a construire pour chaque et ok :)

**Comment by SebLemoine** [comment]
form type ajouté pour projet,event et proposition

**Comment by GuillaumeAV** [comment]
Il manque la capacité à éditer les domaines d'activités ;-)

**Comment by SebLemoine** [comment]
Je vais recréer une issue pour ce cas
