### ISSUE TITLE
Ajuster le zoom / la carte sur le noeud qu'on regarde .. 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#34]
Si je suis sur le noeud commune de Prats, ce serait bien que la carte se centre sur la commune de Prats ...

**Comment by GuillaumeAV** [comment]
C'est trop cool ! 

A ce sujet, Jean Marc suggérait que le bout de code qu'il a écrit, lequel permet d'afficher la carte de manière à ce qu'elle englobe l'ensemble des noeuds, pourrait être pertinent ... Je crois aussi ! Je lui suggère de faire un petit pull request !

**Comment by SebLemoine** [comment]
Je vais créer une autre issue !
