### ISSUE TITLE
Répétition personnes responsables + impliquées

### ISSUE THREAD

**Issue by atantet** [assemblee-virtuelle/Semapps-V1#35]
Sur le port 8080, projet Chemins de la Transition, panneaux "personnes responsables" et "personnes impliquées", chaque personne est répétée 3 fois au lieu d'une.
Même problème concernant les panneaux "document" et "Est concerné par" et "Est amis", "Auteur de" quand on clique sur quelqu'un.
Il semblerait que chaque nouvelle entrée est décuplée.

**Comment by atantet** [comment]
Même problème concernant les panneaux "document" et "Est concerné par"

**Comment by SebLemoine** [comment]
Bonjour ! Normalement résolu, c'étais suite à une mise à jour oublié... merci !
