### ISSUE TITLE
Permettre l'import de données sur toutes les classes 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#37]
J'ai vu que tu avais mis les URI's sur toutes les données, ce qui est trop coool ! 

Maintenant il faut sans doute faire pour toutes les classes ce que tu as fait pour personne ... Facile à ton avis ? Possible dans cette release ? 

Par ailleurs : Ce serait génial de pouvoir importer des thésaurus pour les types d'évent, orgas, etc.

**Comment by SebLemoine** [comment]
Import pour une personne disponible ! Déploiement pour les autres types en cours
