### ISSUE TITLE
Créer les forms bien ou service 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#4]
Pour avoir des livrables et faire du e-commerce ;-)

**Comment by bouviermullerp** [comment]
Il y a peut-être une logique un poil spécifique à construire :
Proposer ou demander un service :
Décrire le service
Décrire la propriété objet : Vendre ? Prêter ? Acheter ? Louer ? (...)
Sans quoi il faudrait créer je crois des classes de type "offering" "demand" etc.

**Comment by GuillaumeAV** [comment]
Par ailleurs, @Lois Antoine j'ai vu que vous aviez mis à jour l'instance GV et que vous aviez notamment inclu les "Biens", c'est trop cool, cependant, on ne peut pas encore en créer, il y a une erreur 500 ! Est-ce que tu pourrais résoudre le bug. Et sinon est-ce que tu t'en es sorti sur les services ?

**Comment by GuillaumeAV** [comment]
To-do **commune à Biens Services, Lieux**, suite au test de création d'un service : 

- Afficher les relations sur la droite (offeredBy - Assemblée Virtuelle ...)
- Afficher les résultats sur la partie publique (dans les onglets afférents) et via le moteur de recherche
- Ajouter mail et téléphone - **sur lieux également**
- Ajouter le bouton éditer dans la partie publique ..
