### ISSUE TITLE
Remplacer "Proposition" par "Article" ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#47]
Ceci est une question ... 

Personne ne s'est jamais véritablement approprié les Propositions ... Il s'agit d'un concept intéressant mais néanmoins assez restrictif, et qui par ailleurs passe souvent par d'autres canaux tels que slack, framavox etc. 

Le concept d'article est quant à lui beaucoup plus large et beaucoup plus usité, il est aujourd'hui présent en tant que type pour document ... 

A chaque fois, dans un article il y a la volonté de faire passer un concept, une analyse, une proposition, un constat etc. 

**La proposition :** 
- Remplacer la classe proposition par la création d'une classe article (de type SIOC:post) 
- Créer des types d'articles : 
Coup de gueule, proposition, analyse, article scientifique etc. 
-> Ce serait le monde des Idées ....

**Comment by SebLemoine** [comment]
same as #62
