### ISSUE TITLE
Voir si on peut saisir les entrées DBPedia en francais ...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#59]
V1 ? V2 ?

**Comment by SebLemoine** [comment]
Pas possible sur dbpedia à l'heure actuel

**Comment by jmvanel** [comment]
Comme je disais, c'est possible,
à condition de charger une partie utile de dbPedia dans SF,
et alors SF va utiliser ça dans son service /lookup , lequel renvoie un format de réponses compatibles avec le service dbPedia lookup.

Tout ça a été testé il y a un an ou 2 environ;
il y a de la doc.:
https://github.com/jmvanel/semantic_forms/blob/master/doc/en/administration.md#populating-with-dbpedia-mirroring-dbpedia

il faudrait probablement adapter les scripts de chargement de dbPedia, car la distribution de dbPedia change un peu au cours du temps.

Une possibilité serait d'utiliser un serveur SF dédié au dbPedia lookup, qui pourrait être utilisé par toute une communauté.
