### ISSUE TITLE
Déconnexion après import d'un profil

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#65]
J'ai importé un profil projet, j'ai appuyé sur Save, ca m'a déconnecté. 
Je me suis reconnecté, j'ai refait l'import j'ai resauvegardé et tout s'est bien passé ... 

Ca m'était déja arrivé, tu sais d'ou ca vient ?

**Comment by SebLemoine** [comment]
Je ne sais pas mais à surveiller

**Comment by SebLemoine** [comment]
Done !
