### ISSUE TITLE
Amis et collaborateurs absent du panneau de droite

### ISSUE THREAD

**Issue by atantet** [assemblee-virtuelle/Semapps-V1#74]
Sur SemMaps 8080, la section "Amis et collaborateurs" est absente du panneau de droite.
En fait il réapparaît une fois que je rajoute des nouveaux amis, mais n'affiche que les nouveaux amis (dans mon cas Jonas, mais pas Guillaume et Liubov).

**Comment by SebLemoine** [comment]
Ok maintenant !
