### ISSUE TITLE
Des labels n'ont pas été pris en compte sur l'instance Assemblée Virtuelle

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/Semapps-V1#84]
Sur l'ensemble des classes j'ai l'impression ... 

description
homepage
about page
hasubject
skill
responsibleOf
employedBy
memberOf
involvedIn
manages
participantOf

**Comment by SebLemoine** [comment]
Je n'ai pas importé l'ontologie sur sf ! Ce n'est pas grands choses :D
